[versions]
aws-sdk = "1.5.114"
kotest = "5.9.1"
slf4j = "2.0.17"

[libraries]
aws-sdk-dynamodb = { group = "aws.sdk.kotlin", name = "dynamodb", version.ref = "aws-sdk" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }