[versions]
aws-sdk = "1.4.123"
slf4j = "2.0.17"

[libraries]
aws-sdk-dynamodb = { group = "aws.sdk.kotlin", name = "dynamodb", version = "aws-sdk" }
2.0.17-simple = { group = "org.2.0.17", name = "2.0.17-simple", version = "2.0.17" }