[versions]
aws-sdk = "1.4.123"
slf4j = "2.0.17"

[libraries]
1.4.124-dynamodb = { group = "aws.sdk.kotlin", name = "dynamodb", version = "1.4.124" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version = "slf4j" }